

baseurl: ""

# Build settings
markdown: kramdown



exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- LICENSE
- README.md

sass:
  style: :compressed
  load_paths:
  - "/home/harald/buildspace/bootstrap/bootstrap-4.1.3/scss"

bootstrap:
  assets: true