

baseurl: "/myblog"

# Build settings
markdown: kramdown



exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- LICENSE
- README.md

#sass:
#  style: compressed

bootstrap:
  assets: true